name: testing the workflow
on: 
  workflow_dispatch: 
    inputs: 
      DEBUG: 
        description: enter if you want debug info
        required: false
        default: 'false'
        type: boolean

      NAME: 
        description: Enter your name
        type: string
        default: 'pradeep'

env: 
  NAME: ${{ github.workflow }}

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps: 
    - name: print github context
    
      if: inputs.DEBUG
      run: |
        echo "trigger by ${{ github.event_name }}"

  env-varaibles: 
    runs-on: windows-latest
    environment: dev
    env: 
      NAME: jobs
    steps: 
     - name: printing the local env varaibles
       run: |
         echo "My name is ${{ env.NAME }}"
       env: 
          NAME: ${{ inputs.NAME }}
     - name: priiting the varaibles
       run: |
         echo "ORG varaibles ${{ vars.ORG_VAR }}"
         echo "Repo var is ${{ vars.REPO_VAR }}"
         echo "env varaible si ${{ vars.DEV_VAR }}"
    
